from enum import Enum

class CategoriaEvento(str, Enum):
    MEDIA = "MEDIA"
    APP_FOREGROUND = "APP_FOREGROUND"
    NOTIFICACAO = "NOTIFICACAO"
    # Categorias para controle interno do sistema
    SISTEMA_PAUSA_INTERACOES = "SISTEMA_PAUSA_INTERACOES"
    SISTEMA_LIBERA_INTERACOES = "SISTEMA_LIBERA_INTERACOES"
    SISTEMA_COMANDO_USUARIO = "SISTEMA_COMANDO_USUARIO"
    MEDIA_COMANDO = "MEDIA_COMANDO"

class TipoAcao(str, Enum):
    NORMAL = "NORMAL"
    INTENCAO_INTERACAO = "INTENCAO_INTERACAO"
    EVENTO_COMPLEXO = "EVENTO_COMPLEXO"
    INTENCAO_RACIOCINIO = "INTENCAO_RACIOCINIO"
    INTENCAO_PESQUISA = "INTENCAO_PESQUISA"
    RESULTADO_PESQUISA = "RESULTADO_PESQUISA"
    GERAR_RESUMO_PERFIL = "GERAR_RESUMO_PERFIL"

class PrioridadeEvento(int, Enum):
    BAIXA = 1
    NORMAL = 2
    ALTA = 3

class OrigemEvento(str, Enum):
    KERNEL = "KERNEL"
    USUARIO = "USUARIO"
    ANDROID = "ANDROID"
    IA = "IA"
    SISTEMA = "SISTEMA"

class EstadoEvento(str, Enum):
    NOVO = "NOVO"
    PENDENTE = "PENDENTE"
    PROCESSANDO = "PROCESSANDO"
    CONCLUIDO = "CONCLUIDO"

class TipoEntidade(str, Enum):
    ARTISTA = "ARTISTA"
    APP = "APP"
    CONTATO = "CONTATO"
